name: graphixui
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http:   # Replace with the latest version
  google_fonts: ^6.2.1
  mobile_scanner:
  qr_flutter:
  google_sign_in: ^6.2.2
  flutter_facebook_auth:
  fluttertoast:
  image_picker:
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  image: ^4.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/google.jpeg
    - assets/ticklogo_white.png
    - assets/Ticklogo_black.png

  # Optional custom fonts section:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
